### ISSUE TITLE
Support for Colorlight and iCESugar-Pro ECP5 boards

### ISSUE THREAD

**Issue by benitoss** [FPGAwars/toolchain-ecp5#1]
Please add the utility **OpenFPGALoader**  (https://github.com/trabucayre/openFPGALoader) in this toolchain for a total support for ColorLight and iCESugar-Pro ECP5 boards
I have created the pull request to IceStudio and Apio to support these boards

I don't know where I  downloaded the OpenFPGAloader.exe file, but you can get the file here -->  https://github.com/benitoss/ColorLight_FPGA_boards/blob/main/Icestudio_update_boards/toolchain-ecp5.zip
The OpenFPGALoader compiled  linux and mac version  you can get here --> https://github.com/YosysHQ/fpga-toolchain/releases/tag/nightly-20210418

There is another utility for ColorLight i5 and iCESugar-Pro called **ECPDAP**  (https://github.com/adamgreig/ecpdap) that you can added in the toolchain, but that program is too slow to program the board. It is recommendable to use an external JTAG programmer as FT2232, FT232H or USB-Blaster to program  these boards and use OpenFPGALoader application to program them.

Regards

**Comment by Obijuan** [comment]
Done!
Now it is time for testing. Initial test will be done in the [apio repo](https://github.com/FPGAwars/apio). So any related issue can be open there
I will write the steps for testing the openFPGAloder in the FPGAwars group
